# -*- coding: utf-8 -*-
"""PyCaret NLP Part-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvkvfv9rcGeTsD8FDS2Gqw-qeQNxEMz4
"""

!pip install pycaret

from pycaret.utils import enable_colab
enable_colab()

from pycaret.datasets import get_data
data = get_data('kiva')

data.shape

data1 = data.sample(1000, random_state=786).reset_index(drop=True)
data1.shape

from pycaret.nlp import *
exp_nlp101 = setup(data=data1, target='en', session_id=123)

lda = create_model('lda')

print(lda)

lda_results = assign_model(lda)
lda_results.head()

plot_model()

plot_model(plot = 'bigram')

plot_model(lda, plot= 'topic_distribution')

plot_model(lda, plot='umap')

evaluate_model(lda)

save_model(lda, 'LDA Model')